spring.application.name=TextAdventureApp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.configuration.map-underscore-to-camel-case=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true