

# ===============================
# H2 ?????????
# ===============================
spring.datasource.url=jdbc:h2:mem:renderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# ===============================
# schema.sql ?????
# ===============================
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# ===============================
# H2 Console??????????
# ===============================
spring.h2.console.enabled=false
# ===============================
# Server
# ===============================
server.port=8080
