version: '3.8'

services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DB_PASSWORD}
      MYSQL_DATABASE: mydb
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
